### ISSUE TITLE
Dependency versions are not pinned

### ISSUE THREAD

**Issue by AnthonyMikh** [Rimpampa/langton_ant-rs#2]
Right now `Cargo.toml` contains the following:

```toml
[dependencies]
rand = "*"
```

It means that in order to build the crate cargo will use the latest version of `rand` if `Cargo.lock` is not present. `rand` is still under heavy development and new major versions are released occasionally, so build can easily brake in future. To avoid it, lock the version:

```toml
[dependencies]
rand = "0.6"
```

This will prevent build from braking while still allowing to accepts patch updates.
